TrajectoryPlannerROS:
  max_vel_x: 1
  min_vel_x: 0.7
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.8
  escape_vel: -0.6

  acc_lim_theta: 1
  acc_lim_x: 1
  acc_lim_y: 1
  yaw_goal_tolerance: 0.5

  holonomic_robot: false
