
footprint: [[0.26, 0.16], [0.26, -0.16], [-0.26, -0.16], [-0.26, 0.16]]

#robot_radius: ir_of_robot
inflation_radius: 0.2

plugins:
  - {name: obstacles_2d,      type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}

obstacles_2d:
  enabled:                true
  origin_z:               0.0    # meters
  z_resolution:           0.02
  combination_method:     1      # 1=max, 0=override
  track_unknown_space:    true   # default space is unknown
  obstacle_range:         5.0    # meters
  raytrace_range:         5.1
  observation_sources: laserscan
  laserscan:
    data_type: LaserScan
    topic: isabelle/laserscan
    sensor_frame: laser
    # expected_update_rate: 0.05 # VERY conservative, actual is ~700Hz
    #observation_persistence: 0.0
    marking: true
    clearing: true
    max_obstacle_height: 2.0
    min_obstacle_height: 0.008
