obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.1, 0.1], [0.1, -0.1], [-0.1, -0.1], [-0.1, 0.1]]

#robot_radius: ir_of_robot
inflation_radius: 0.1

plugins:
  - {name: obstacles_2d,      type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}

obstacles_2d:
  enabled:                true
  origin_z:               0.0    # meters
  z_resolution:           0.2
  combination_method:     1      # 1=max, 0=override
  track_unknown_space:    true   # default space is unknown
  obstacle_range:         3.0    # meters
  raytrace_range:         3.5
  observation_sources: laserscan
  laserscan:
    data_type: LaserScan
    topic: isabelle/laserscan
    sensor_frame: hokuyo_link
    # expected_update_rate: 0.05 # VERY conservative, actual is ~700Hz
    # observation_persistence: 0.0
    marking: true
    clearing: true
    max_obstacle_height: 2.0
    min_obstacle_height: 0.0
