<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="isabelle">
   
    <xacro:property name="robot" value="isabelle"/>
    <!-- physical parameters of robot, all in SI (meters, kg) -->
    <!-- base dimensions -->
    <xacro:property name="base_mass" value="2.26796" />
    <xacro:property name="base_width" value="0.1524" />     <!-- width=y -->
    <xacro:property name="base_length" value="0.254" />    <!-- length=x -->
    <xacro:property name="base_height" value="0.04" />     <!-- height=z -->
    <!-- wheel properties -->
    <xacro:property name="wheel_radius" value="0.02921" />
    <xacro:property name="wheel_width" value="0.0254" />
    <!-- differential properties -->
    <xacro:property name="wheel_mass" value="0.45" />
    <xacro:property name="wheelbase" value="0.19668" />
    <xacro:property name="track_width" value="0.18" />
    <xacro:property name="wheel_offset_x" value="${wheelbase / 2}" />
    <xacro:property name="wheel_offset_y" value="${track_width / 2}" />
    <xacro:property name="wheel_offset_z" value="-0.01079" />
    <!-- lidar properties -->
    <xacro:property name="lidar_mass" value="0.830" />
    <xacro:property name="lidar_height" value="0.0762" />
    <xacro:property name="lidar_width" value="0.0508" />
    <xacro:property name="lidar_offset_x" value="0.0" />
    <xacro:property name="lidar_offset_y" value="0.0" />
    <xacro:property name="lidar_offset_z" value="0.0481" />
    <!-- imu properties -->
    <xacro:property name="imu_offset_x" value="0.0" />
    <xacro:property name="imu_offset_y" value="0.0" />
    <xacro:property name="imu_offset_z" value="0.0" />

    <!--
        Include other xacro files for simulation plugins, Gazebo references, and macros
    -->
    <xacro:include filename="$(find isabelle_sim)/models/isabelle_2/model.gazebo" />
    <xacro:include filename="$(find isabelle_sim)/models/isabelle_2/model.macro" />

    <!-- 
        objects contained within the gazebo tags are for Gazebo simulation use only, ignored otherwise.
        They use SDF format, rather than URDF format
    -->
    <gazebo>
        <static>false</static>
    </gazebo>
    
    <!-- base link (the box) -->
    <xacro:box_total name="base_link" mass="${base_mass}" width="${base_width}" length="${base_length}" height="${base_height}"/>

    <!-- front left wheel -->
    <xacro:wheel name="front_left_wheel" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}" wheel_mass="${wheel_mass}"/>
    <xacro:wheel_joint name="front_left_wheel" x_offset="${wheel_offset_x}" y_offset="${wheel_offset_y}" z_offset="${wheel_offset_z}" reflect_x="1" reflect_y="1"/>

    <xacro:wheel name="front_right_wheel" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}" wheel_mass="${wheel_mass}"/>
    <xacro:wheel_joint name="front_right_wheel" x_offset="${wheel_offset_x}" y_offset="${wheel_offset_y}" z_offset="${wheel_offset_z}" reflect_x="1" reflect_y="-1"/>


    <!-- back left caster -->
    <xacro:caster_total name="back_left_caster" radius="${wheel_radius}" mass="${wheel_mass}" />
    <xacro:caster_joint name="back_left_caster" x_offset="${wheel_offset_x}" y_offset="${wheel_offset_y}" z_offset="${wheel_offset_z}" reflect_x="-1" reflect_y="1"/>

    <!-- back right caster -->
    <xacro:caster_total name="back_right_caster" radius="${wheel_radius}" mass="${wheel_mass}" />
    <xacro:caster_joint name="back_right_caster" x_offset="${wheel_offset_x}" y_offset="${wheel_offset_y}" z_offset="${wheel_offset_z}" reflect_x="-1" reflect_y="-1"/>
    
    <!-- lidar link -->
    <xacro:box_total name="laser" mass="${lidar_mass}" width="${lidar_width}" height="${lidar_height}" length="${lidar_width}"/>
    <joint name="laser_joint" type="fixed">
        <gazebo reference="laser_joint">
        </gazebo>
        <parent link="base_link"/>
        <child link="laser"/>
        <origin xyz="${lidar_offset_x} ${lidar_offset_y} ${lidar_offset_z}" rpy="0 0 0" />
    </joint>

    <!-- imu link -->
    <xacro:box_total name="imu_link" mass="0.05" width="0.01" height="0.01" length="0.01"/>
    <joint name="imu_joint" type="fixed">
        <gazebo reference="imu_joint">
        </gazebo>
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="${imu_offset_x} ${imu_offset_y} ${imu_offset_z}" rpy="0 0 0" />
    </joint>

</robot>
