local_costmap:
  global_frame: odom
  robot_base_frame: chassis
  update_frequency: 5.0
  publish_frequency: 2.0
  
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
 
  # - {name: obstacle_layer,     type: "costmap_2d::ObstacleLayer"}
  plugins:
    - {name: static_layer,       type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,    type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}

  static_layer:
    enabled:                true
    map_topic:              "/map"

  inflation_layer:
    enabled:                true
    cost_scaling_factor:    5
    inflation_radius:       0.3
  
  obstacle_layer:
    observation_sources: hokuyo_link
    footprint_clearing_enabled: true
    laser_scan_sensor: {data_type: laserscan, sensor_frame: chassis, clearing: true, marking: true, topic: /laserscan}